reason_matrix_dict = [{'REASON OF TRANSFER': 'DD Delivery',
  'Descriptive Reason of Transfer': 'Customer will say it is a furniture item and he wants to change the delivery time, received faulty, book a slot',
  'DEPARTMENT': ' UK Telebooking',
  'Dept(transfermatrix)': 'TP',
  'Handled by': 'UK',
  'Queue Name': 'Branded',
  'Comments': '',
  'Queue Name Display on Genesys': 'X Branded'},
 {'REASON OF TRANSFER': 'Account Closure',
  'Descriptive Reason of Transfer': 'Customer called to close the account',
  'DEPARTMENT': 'Account Closure',
  'Dept(transfermatrix)': '',
  'Handled by': 'UK & Pune',
  'Queue Name': 'UK Enquiries',
  'Comments': 'If not trained',
  'Queue Name Display on Genesys': 'X  Enquiries'},
 {'REASON OF TRANSFER': 'N-Orders (Store Calling - Parcel anything apart from At Shop )',
  'Descriptive Reason of Transfer': 'Customer has placed the order, but not able to see in the history. Order no starting with N.',
  'DEPARTMENT': 'Advise the Store to speak with the store manager. Offer a refund/ reorder at the store',
  'Dept(transfermatrix)': '',
  'Handled by': 'UK',
  'Queue Name': 'N - Orders we only track the order and any refund/ Replacement need to dela by store',
  'Comments': 'If not trained can be transfer to Enq',
  'Queue Name Display on Genesys': 'X  Enquiries'},
 {'REASON OF TRANSFER': 'Accounts blocked with AIT investigation',
  'Descriptive Reason of Transfer': 'Customer called as he received an email saying the account is blocked.',
  'DEPARTMENT': 'AIT TEAM (Fraud) (Warm transfer)',
  'Dept(transfermatrix)': 'CCAIT',
  'Handled by': 'UK',
  'Queue Name': 'AIT',
  'Comments': 'Warm transfer',
  'Queue Name Display on Genesys': 'X AIT'},
 {'REASON OF TRANSFER': 'Accounts opened without consent',
  'Descriptive Reason of Transfer': 'Customer called to inform that an account is open with their details fraudulently',
  'DEPARTMENT': 'AIT TEAM (Fraud) (Warm transfer)',
  'Dept(transfermatrix)': 'CCAIT',
  'Handled by': 'UK',
  'Queue Name': 'AIT',
  'Comments': 'Warm transfer',
  'Queue Name Display on Genesys': 'X AIT'},
 {'REASON OF TRANSFER': "Orders placed on the account without customer's consent",
  'Descriptive Reason of Transfer': 'Customer called to inform that an order is placed fraudulently',
  'DEPARTMENT': 'AIT TEAM (Fraud) (Warm transfer)',
  'Dept(transfermatrix)': 'CCAIT',
  'Handled by': 'UK',
  'Queue Name': 'AIT',
  'Comments': 'Warm transfer',
  'Queue Name Display on Genesys': 'X AIT'},
 {'REASON OF TRANSFER': 'Bank/Directory card used without consent',
  'Descriptive Reason of Transfer': 'Customer called to inform that his/her Bank/Directory card fraudulently',
  'DEPARTMENT': 'AIT TEAM (Fraud) (Warm transfer)',
  'Dept(transfermatrix)': 'CCAIT',
  'Handled by': 'UK',
  'Queue Name': 'AIT',
  'Comments': 'Warm transfer',
  'Queue Name Display on Genesys': 'X AIT'},
 {'REASON OF TRANSFER': "Details changed on account without customer's consent",
  'Descriptive Reason of Transfer': 'Customer called to inform that his/her details account details has been updated fraudulently',
  'DEPARTMENT': 'AIT TEAM (Fraud) (Warm transfer)',
  'Dept(transfermatrix)': 'CCAIT',
  'Handled by': 'UK',
  'Queue Name': 'AIT',
  'Comments': 'Warm transfer',
  'Queue Name Display on Genesys': 'X AIT'},
 {'REASON OF TRANSFER': 'Long term occupier calling for customer not known at address, based on an application letter being received',
  'Descriptive Reason of Transfer': 'Customer states that he has receieved a letter at his address for some other customer. And the customer does not reside at that address.',
  'DEPARTMENT': 'AIT TEAM (Fraud) (Warm transfer)',
  'Dept(transfermatrix)': 'CCAIT',
  'Handled by': 'UK',
  'Queue Name': 'UK Enquiries',
  'Comments': 'Will set up Gone away on the acocunt. If nt trained can be transfer to Enq',
  'Queue Name Display on Genesys': 'X  Enquiries'},
 {'REASON OF TRANSFER': 'Giftcard placed on hold for investigation',
  'Descriptive Reason of Transfer': 'Customer called as he received an email saying the giftcard is placed on hold',
  'DEPARTMENT': 'AIT TEAM (Fraud) (Warm transfer)',
  'Dept(transfermatrix)': 'CCAIT',
  'Handled by': 'UK',
  'Queue Name': 'Gift card team',
  'Comments': '',
  'Queue Name Display on Genesys': 'X gift card'},
 {'REASON OF TRANSFER': 'N3step AIT Calls',
  'Descriptive Reason of Transfer': 'All N3S accounts to be transferred',
  'DEPARTMENT': 'AIT TEAM (Fraud) (Warm transfer)',
  'Dept(transfermatrix)': 'CCAIT',
  'Handled by': 'UK',
  'Queue Name': 'Pay in 3 AIT',
  'Comments': '',
  'Queue Name Display on Genesys': 'X Pay in 3 AIT'},
 {'REASON OF TRANSFER': 'Increasing / Decreasing Credit Limits',
  'Descriptive Reason of Transfer': 'Customer calls to understand the increase or decrease in credit limit',
  'DEPARTMENT': 'C/L Query',
  'Dept(transfermatrix)': 'Enquiries',
  'Handled by': 'UK & Pune',
  'Queue Name': 'UK Enquiries',
  'Comments': 'If not trained',
  'Queue Name Display on Genesys': 'X  Enquiries'},
 {'REASON OF TRANSFER': 'DRL Orders( only when orders are not going through on their account)',
  'Descriptive Reason of Transfer': 'DRL Orders( only when orders are not going through on their account)',
  'DEPARTMENT': 'CC Payment Queries',
  'Dept(transfermatrix)': 'Enquiries',
  'Handled by': 'UK & Pune',
  'Queue Name': '',
  'Comments': '',
  'Queue Name Display on Genesys': ''},
 {'REASON OF TRANSFER': 'Customer calls to speak to the store',
  'Descriptive Reason of Transfer': 'Customer calls to speak to the store',
  'DEPARTMENT': 'Check if query can be resolved If still required a transfer- Dial 35(Store number)',
  'Dept(transfermatrix)': '',
  'Handled by': 'UK & Pune',
  'Queue Name': 'Specific Store',
  'Comments': 'First need to check the reason for transferring to the store. If still required then dial Store number and transfer',
  'Queue Name Display on Genesys': 'Dial Store number on Genesys'},
 {'REASON OF TRANSFER': 'Collection Not Actioned (  2 or more failed collections )',
  'Descriptive Reason of Transfer': 'Customer says : I have arranged for collection multiple time (2 times) and failed',
  'DEPARTMENT': 'Transfer to SET ( Senior Enquiries Tam)',
  'Dept(transfermatrix)': 'Enquiries',
  'Handled by': 'UK',
  'Queue Name': 'Escalated Enquiries',
  'Comments': 'Warm transfer',
  'Queue Name Display on Genesys': 'X Escalated Enquiries'},
 {'REASON OF TRANSFER': 'Pending Order',
  'Descriptive Reason of Transfer': 'Customer called as he received an email saying that some security is needed to release the order.',
  'DEPARTMENT': 'Credit',
  'Dept(transfermatrix)': 'CCAIT',
  'Handled by': 'UK & Pune',
  'Queue Name': 'Credit',
  'Comments': 'Warm transfer',
  'Queue Name Display on Genesys': 'X Credit'},
 {'REASON OF TRANSFER': 'Credit Suspension Query',
  'Descriptive Reason of Transfer': 'Credit Suspension Query',
  'DEPARTMENT': 'Credit',
  'Dept(transfermatrix)': 'CCAIT',
  'Handled by': 'UK',
  'Queue Name': 'Credit',
  'Comments': 'Warm transfer',
  'Queue Name Display on Genesys': 'X Credit'},
 {'REASON OF TRANSFER': 'Account Match',
  'Descriptive Reason of Transfer': 'Account Match',
  'DEPARTMENT': 'Credit',
  'Dept(transfermatrix)': 'CCAIT',
  'Handled by': 'UK & Pune',
  'Queue Name': '',
  'Comments': '',
  'Queue Name Display on Genesys': ''},
 {'REASON OF TRANSFER': 'Store calling for Authorisation code',
  'Descriptive Reason of Transfer': 'Store referral calls. Store attendant calls and advisor confirms if the call is regarding store card referral',
  'DEPARTMENT': 'Credit - Account Queries - Store Cards',
  'Dept(transfermatrix)': 'CCAIT',
  'Handled by': 'Pune',
  'Queue Name': 'Credit',
  'Comments': 'Store attendant call for the Authorisation code',
  'Queue Name Display on Genesys': 'X Credit'},
 {'REASON OF TRANSFER': 'Blocked Account by the Credit Department- Credit Hold',
  'Descriptive Reason of Transfer': 'credit decrease, customer not able to use the credit , Made payment on time but credit limit is not same',
  'DEPARTMENT': 'Credit/ Blocked Account by Credit Team',
  'Dept(transfermatrix)': 'CCAIT',
  'Handled by': 'UK & Pune',
  'Queue Name': 'Credit',
  'Comments': 'Warm transfer',
  'Queue Name Display on Genesys': 'X Credit'},
 {'REASON OF TRANSFER': 'Account Opened by customer under 18 yrs of age Accounts Matched',
  'Descriptive Reason of Transfer': 'Account Opened by customer under 18 yrs of age Accounts Matched',
  'DEPARTMENT': 'Credit/ Bureau Check Query',
  'Dept(transfermatrix)': 'CCAIT',
  'Handled by': 'UK',
  'Queue Name': 'Credit',
  'Comments': 'Warm transfer',
  'Queue Name Display on Genesys': 'X Credit'},
 {'REASON OF TRANSFER': 'Pended/Scheduled Orders',
  'Descriptive Reason of Transfer': 'Customer called as he received an email saying that some security is needed to release the order.',
  'DEPARTMENT': 'Credit/ Pended Orders',
  'Dept(transfermatrix)': 'CCAIT',
  'Handled by': 'UK & Pune',
  'Queue Name': 'Credit',
  'Comments': 'Warm transfer',
  'Queue Name Display on Genesys': 'X Credit'},
 {'REASON OF TRANSFER': 'Declined Credit Accounts',
  'Descriptive Reason of Transfer': 'Customer says I am not able to open credit account ',
  'DEPARTMENT': 'Credit/ Withdrawn Support',
  'Dept(transfermatrix)': 'CCAIT',
  'Handled by': 'UK',
  'Queue Name': 'Credit',
  'Comments': 'Warm transfer',
  'Queue Name Display on Genesys': 'X Credit'},
 {'REASON OF TRANSFER': 'Queries regarding cancelled orders',
  'Descriptive Reason of Transfer': 'Iguide will have cancel - 001 - Advisor investigates and transfers to CCAIT',
  'DEPARTMENT': 'Credit/Cancelled Orders',
  'Dept(transfermatrix)': 'CCAIT',
  'Handled by': 'UK',
  'Queue Name': 'Credit',
  'Comments': 'Warm transfer',
  'Queue Name Display on Genesys': 'X Credit'},
 {'REASON OF TRANSFER': 'Orders Over Credit Limit',
  'Descriptive Reason of Transfer': 'Orders Over Credit Limit',
  'DEPARTMENT': 'Credit/Over C/L Pop up',
  'Dept(transfermatrix)': 'CCAIT',
  'Handled by': 'UK & Pune',
  'Queue Name': 'Credit',
  'Comments': 'Warm transfer',
  'Queue Name Display on Genesys': 'X Credit'},
 {'REASON OF TRANSFER': 'Injury due to a product',
  'Descriptive Reason of Transfer': "Customer informed that NEXT's product caused injury",
  'DEPARTMENT': 'CET',
  'Dept(transfermatrix)': 'CRMT',
  'Handled by': 'UK',
  'Queue Name': 'CET',
  'Comments': 'Warm transfer',
  'Queue Name Display on Genesys': 'X Online CET'},
 {'REASON OF TRANSFER': 'Customer has a Reference Number for the Complaint',
  'Descriptive Reason of Transfer': 'Customer has a Reference Number for the Complaint',
  'DEPARTMENT': 'CET',
  'Dept(transfermatrix)': 'CRMT',
  'Handled by': 'UK',
  'Queue Name': 'CET',
  'Comments': 'Warm transfer',
  'Queue Name Display on Genesys': 'X Online CET'},
 {'REASON OF TRANSFER': 'Direct Debit',
  'Descriptive Reason of Transfer': 'Customer wanted to setup/amend/cancel direct debit',
  'DEPARTMENT': 'Direct Debit',
  'Dept(transfermatrix)': 'Enquiries',
  'Handled by': 'Pune',
  'Queue Name': 'Direct debit',
  'Comments': 'If nt trained',
  'Queue Name Display on Genesys': 'X Direct Debit'},
 {'REASON OF TRANSFER': 'Expired Directory Card',
  'Descriptive Reason of Transfer': 'Customer says that this directory card (next pay card)  is expired',
  'DEPARTMENT': 'Enquiries',
  'Dept(transfermatrix)': 'Enquiries',
  'Handled by': 'UK & Pune',
  'Queue Name': 'Enquires',
  'Comments': 'If not trained',
  'Queue Name Display on Genesys': 'X  Enquiries'},
 {'REASON OF TRANSFER': 'Closing an Account',
  'Descriptive Reason of Transfer': 'Customer called to close the account',
  'DEPARTMENT': 'Enquiries',
  'Dept(transfermatrix)': 'Enquiries',
  'Handled by': 'UK & Pune',
  'Queue Name': 'Enquires',
  'Comments': 'If not trained',
  'Queue Name Display on Genesys': 'X  Enquiries'},
 {'REASON OF TRANSFER': 'VIP Sales ( If customer not happy with slots or have not received VIP Invite )',
  'Descriptive Reason of Transfer': 'VIP Sales ( If customer not happy with slots or have not received VIP Invite )',
  'DEPARTMENT': 'Enquiries',
  'Dept(transfermatrix)': 'Enquiries',
  'Handled by': 'UK & Pune',
  'Queue Name': 'Pune Team',
  'Comments': 'Not to Transfer',
  'Queue Name Display on Genesys': ''},
 {'REASON OF TRANSFER': 'NEXT Branded Small Electrical Items, delivered by Hermes or Purchased at a Store',
  'Descriptive Reason of Transfer': 'NEXT Branded Small Electrical Items, delivered by Hermes or Purchased at a Store - Light & Large item are delivered by evri as it can be handled by 1 man',
  'DEPARTMENT': 'Enquiries',
  'Dept(transfermatrix)': 'Enquiries',
  'Handled by': 'UK',
  'Queue Name': 'Branded Team',
  'Comments': '',
  'Queue Name Display on Genesys': 'X Branded'},
 {'REASON OF TRANSFER': 'Query regarding PPI on the Directory Card',
  'Descriptive Reason of Transfer': 'Query regarding PPI on the Directory Card',
  'DEPARTMENT': 'Enquiries',
  'Dept(transfermatrix)': 'Enquiries',
  'Handled by': 'UK',
  'Queue Name': '',
  'Comments': '',
  'Queue Name Display on Genesys': ''},
 {'REASON OF TRANSFER': 'DPD Queries',
  'Descriptive Reason of Transfer': 'Customer will say item is not delivered',
  'DEPARTMENT': 'Enquiries',
  'Dept(transfermatrix)': 'Enquiries',
  'Handled by': 'UK & Pune',
  'Queue Name': 'Pune Team',
  'Comments': 'Not to transfer',
  'Queue Name Display on Genesys': ''},
 {'REASON OF TRANSFER': 'ParcelShop Queries',
  'Descriptive Reason of Transfer': 'ParcelShop Queries',
  'DEPARTMENT': 'Enquiries',
  'Dept(transfermatrix)': 'Enquiries',
  'Handled by': 'UK & Pune',
  'Queue Name': 'Pune Team',
  'Comments': 'Not to transfer',
  'Queue Name Display on Genesys': ''},
 {'REASON OF TRANSFER': 'Query on International Retail order',
  'Descriptive Reason of Transfer': 'Query on International Retail order',
  'DEPARTMENT': 'International',
  'Dept(transfermatrix)': 'International',
  'Handled by': 'ROW',
  'Queue Name': 'International ',
  'Comments': '',
  'Queue Name Display on Genesys': 'X International'},
 {'REASON OF TRANSFER': 'If the customer is not willing to visit the store',
  'Descriptive Reason of Transfer': 'If the customer is not willing to visit the store',
  'DEPARTMENT': 'Enquiries',
  'Dept(transfermatrix)': 'Enquiries',
  'Handled by': 'UK/Pune',
  'Queue Name': 'Pune Team',
  'Comments': 'Not to transfer',
  'Queue Name Display on Genesys': ''},
 {'REASON OF TRANSFER': 'Faulty Item',
  'Descriptive Reason of Transfer': 'Faulty Item',
  'DEPARTMENT': 'Faulty Items',
  'Dept(transfermatrix)': 'Enquiries',
  'Handled by': 'Pune',
  'Queue Name': 'Pune Team',
  'Comments': 'Not to transfer',
  'Queue Name Display on Genesys': ''},
 {'REASON OF TRANSFER': 'Flower Query',
  'Descriptive Reason of Transfer': 'Flower Query',
  'DEPARTMENT': 'Flower Enquiries',
  'Dept(transfermatrix)': 'Enquiries',
  'Handled by': 'Pune',
  'Queue Name': 'Flower Enquiries',
  'Comments': 'If nt trained',
  'Queue Name Display on Genesys': 'X flower Enquiries'},
 {'REASON OF TRANSFER': 'Gift Card Query',
  'Descriptive Reason of Transfer': 'Gift Card Query',
  'DEPARTMENT': 'Gift Card Enquiries',
  'Dept(transfermatrix)': 'Enquiries',
  'Handled by': 'UK',
  'Queue Name': 'Gift Card Team',
  'Comments': 'X gift Card',
  'Queue Name Display on Genesys': ''},
 {'REASON OF TRANSFER': 'Request to speak to the HR Department',
  'Descriptive Reason of Transfer': 'Request to speak to the HR Department',
  'DEPARTMENT': 'Give email address- RetailHR_Admin@next.co.uk',
  'Dept(transfermatrix)': '',
  'Handled by': 'UK',
  'Queue Name': 'Next headoffice',
  'Comments': '',
  'Queue Name Display on Genesys': 'Next headoffice Reception'},
 {'REASON OF TRANSFER': 'Goods Not Received',
  'Descriptive Reason of Transfer': 'Goods Not Received',
  'DEPARTMENT': 'GNR',
  'Dept(transfermatrix)': 'Enquiries',
  'Handled by': 'Pune',
  'Queue Name': 'Pune Team',
  'Comments': 'If nt trained GNR',
  'Queue Name Display on Genesys': ''},
 {'REASON OF TRANSFER': 'Tracking an Order / Parcel',
  'Descriptive Reason of Transfer': 'Customer wanted to track an order',
  'DEPARTMENT': 'GNR',
  'Dept(transfermatrix)': 'Enquiries',
  'Handled by': 'Pune',
  'Queue Name': 'Pune Team',
  'Comments': 'If nt trained GNR',
  'Queue Name Display on Genesys': ''},
 {'REASON OF TRANSFER': 'Home item regarding complaints',
  'Descriptive Reason of Transfer': 'Home item regarding complaints',
  'DEPARTMENT': 'HCRMT (Warm transfer) ',
  'Dept(transfermatrix)': 'CRMT',
  'Handled by': 'UK',
  'Queue Name': 'Home CET',
  'Comments': '',
  'Queue Name Display on Genesys': 'X home CET'},
 {'REASON OF TRANSFER': 'Faulty Home Items',
  'Descriptive Reason of Transfer': 'Faulty Home Items',
  'DEPARTMENT': 'Home',
  'Dept(transfermatrix)': 'Home',
  'Handled by': 'UK',
  'Queue Name': 'Home Pune Faulty',
  'Comments': '',
  'Queue Name Display on Genesys': 'X Pune Faulty Home'},
 {'REASON OF TRANSFER': 'Home Item Query',
  'Descriptive Reason of Transfer': 'Home Item Query',
  'DEPARTMENT': 'Home',
  'Dept(transfermatrix)': 'Home',
  'Handled by': 'UK',
  'Queue Name': 'UK telebooking',
  'Comments': '',
  'Queue Name Display on Genesys': 'X UK Telebooking'},
 {'REASON OF TRANSFER': 'Delivery Query of Light and Large items, delivered by next day to Store Vans',
  'Descriptive Reason of Transfer': 'Delivery Query of Light and Large items, delivered by next day to Store Vans',
  'DEPARTMENT': 'Home',
  'Dept(transfermatrix)': 'Home',
  'Handled by': 'UK',
  'Queue Name': '',
  'Comments': '',
  'Queue Name Display on Genesys': ''},
 {'REASON OF TRANSFER': 'Home Item Query not available on the Website',
  'Descriptive Reason of Transfer': 'Home Item Query not available on the Website',
  'DEPARTMENT': 'Home',
  'Dept(transfermatrix)': 'Home',
  'Handled by': 'UK',
  'Queue Name': 'Home Team',
  'Comments': '',
  'Queue Name Display on Genesys': 'X Home'},
 {'REASON OF TRANSFER': 'Personalised gift',
  'Descriptive Reason of Transfer': 'Advisor will see it on the order list and transfer it to home',
  'DEPARTMENT': 'Home Personalized Gift/Team',
  'Dept(transfermatrix)': 'Home',
  'Handled by': 'UK',
  'Queue Name': 'Personalised Team',
  'Comments': '',
  'Queue Name Display on Genesys': 'X Personalised'},
 {'REASON OF TRANSFER': 'DD Delivery But Personalised',
  'Descriptive Reason of Transfer': 'Advisor will see it on the order list and transfer it to home',
  'DEPARTMENT': 'Home Personalized Gift/Team',
  'Dept(transfermatrix)': 'Home',
  'Handled by': 'UK',
  'Queue Name': 'Personalised Team',
  'Comments': '',
  'Queue Name Display on Genesys': 'X Personalised'},
 {'REASON OF TRANSFER': 'Made to Measure Curtains/ Blinds',
  'Descriptive Reason of Transfer': 'Advisor will see it on the order list and transfer it to home',
  'DEPARTMENT': 'Home product Management',
  'Dept(transfermatrix)': 'Home',
  'Handled by': 'UK',
  'Queue Name': 'Branded',
  'Comments': '',
  'Queue Name Display on Genesys': 'X Branded (IVR - Press 1)'},
 {'REASON OF TRANSFER': 'Store calling to track order Home or Store Delivery (POS Rollout worktype)',
  'Descriptive Reason of Transfer': 'Store calling to track order Home or Store Delivery (POS Rollout worktype)',
  'DEPARTMENT': 'If not trained on worktype please transfer to relevant Dept i.e Store services for Store delivery, GNR for Home Delivery',
  'Dept(transfermatrix)': '',
  'Handled by': 'Pune',
  'Queue Name': 'Pune Team',
  'Comments': 'If nt trained then Store Service for store order and GNR for online order',
  'Queue Name Display on Genesys': 'X Store Customer calls'},
 {'REASON OF TRANSFER': 'Store calling - Customer want to cancel the Order',
  'Descriptive Reason of Transfer': 'Store calling - Customer want to cancel the Order',
  'DEPARTMENT': 'If retail order- Advise them to cancel in Store/ Online orders deal as normal',
  'Dept(transfermatrix)': '',
  'Handled by': 'UK/Pune',
  'Queue Name': 'Pune Team',
  'Comments': 'Not to Transfer. If retail order- Advise them to cancel in Store/ Online orders deal as normal',
  'Queue Name Display on Genesys': '-'},
 {'REASON OF TRANSFER': 'Refund Not Received on the International Account',
  'Descriptive Reason of Transfer': 'Refund Not Received on the International Account - Advisor can probe and check from the account',
  'DEPARTMENT': 'International',
  'Dept(transfermatrix)': 'International',
  'Handled by': 'ROW',
  'Queue Name': 'International ',
  'Comments': '',
  'Queue Name Display on Genesys': 'X International'},
 {'REASON OF TRANSFER': 'Techincal Issue with the Next Website',
  'Descriptive Reason of Transfer': 'Techincal Issue on Next Website, Will try to deal if it is basic or password reset',
  'DEPARTMENT': 'Internet Helpline',
  'Dept(transfermatrix)': 'Enquiries',
  'Handled by': 'Pune',
  'Queue Name': 'Internet helpline',
  'Comments': 'If nt trained',
  'Queue Name Display on Genesys': 'X Internet Helpline'},
 {'REASON OF TRANSFER': 'Light and Large Delivery',
  'Descriptive Reason of Transfer': 'Customer will say he ordered lamp, bedhseets, curtains, cushions, home decoration .',
  'DEPARTMENT': 'Light & Large',
  'Dept(transfermatrix)': '',
  'Handled by': 'UK',
  'Queue Name': 'Pune Team',
  'Comments': 'Not to Transfer',
  'Queue Name Display on Genesys': ''},
 {'REASON OF TRANSFER': 'Store calling for POS number',
  'Descriptive Reason of Transfer': 'Store calling for POS number',
  'DEPARTMENT': "Locate the POS No on website with the help of item description, if not able to locate, ask the S/A to speak with Store Manager as it would be the manager's descretion",
  'Dept(transfermatrix)': '',
  'Handled by': 'UK/Pune',
  'Queue Name': 'Pune Team',
  'Comments': "Locate the POS No on website with the help of item description, if not able to locate, ask the S/A to speak with Store Manager as it would be the manager's descretion",
  'Queue Name Display on Genesys': ''},
 {'REASON OF TRANSFER': 'Vulnerable Customer who are not claiming financial difficulties',
  'Descriptive Reason of Transfer': 'Vulnerable Customer who are not claiming financial difficulties',
  'DEPARTMENT': 'Customer Care Team (Warm transfer)',
  'Dept(transfermatrix)': '',
  'Handled by': 'UK',
  'Queue Name': 'Collection Team',
  'Comments': '',
  'Queue Name Display on Genesys': 'X collections'},
 {'REASON OF TRANSFER': 'Account charges',
  'Descriptive Reason of Transfer': 'Account charges',
  'DEPARTMENT': 'Payment / Account Queries',
  'Dept(transfermatrix)': 'Enquiries',
  'Handled by': 'UK/Pune',
  'Queue Name': 'UK Enquiries',
  'Comments': 'If query on Interest charges then UK enq/ Refin query then deal as normal',
  'Queue Name Display on Genesys': 'X Enquiries'},
 {'REASON OF TRANSFER': 'Payment / Account Query',
  'Descriptive Reason of Transfer': 'Payment / Account Query',
  'DEPARTMENT': 'Payment / Account Queries',
  'Dept(transfermatrix)': 'Enquiries',
  'Handled by': 'UK/Pune',
  'Queue Name': 'UK Enquiries',
  'Comments': '',
  'Queue Name Display on Genesys': 'X Enquiries'},
 {'REASON OF TRANSFER': 'Store Calling for TILL Issue',
  'Descriptive Reason of Transfer': 'Store Calling for TILL Issue - Store attendant will call and say that they are not able to localte the locker due to till issue.',
  'DEPARTMENT': 'POS Control',
  'Dept(transfermatrix)': 'Non-Operation',
  'Handled by': 'UK',
  'Queue Name': '',
  'Comments': '',
  'Queue Name Display on Genesys': ''},
 {'REASON OF TRANSFER': 'Customer wants to Cancel the Delivery ( Furniture )',
  'Descriptive Reason of Transfer': 'Customer wants to Cancel the Delivery ( Furniture )',
  'DEPARTMENT': 'Pune telbooking',
  'Dept(transfermatrix)': 'Home',
  'Handled by': 'Pune',
  'Queue Name': 'Pune Team',
  'Comments': 'Apply Macro',
  'Queue Name Display on Genesys': ''},
 {'REASON OF TRANSFER': 'Complaint regarding store',
  'Descriptive Reason of Transfer': 'Complaint regarding store - store staff rude behaviour, stolen, theft,  etc anything happenned on store',
  'DEPARTMENT': 'RCET Retail Complaint Resolution (Warm transfer)',
  'Dept(transfermatrix)': 'CRMT',
  'Handled by': 'UK',
  'Queue Name': 'Retail CCT',
  'Comments': '',
  'Queue Name Display on Genesys': 'X RES Customer CET'},
 {'REASON OF TRANSFER': 'Customer has a Reference Number for the retail Complaint',
  'Descriptive Reason of Transfer': 'Customer has a Reference Number for the retail Complaint',
  'DEPARTMENT': 'RCET Retail Complaint Resolution (Warm transfer)',
  'Dept(transfermatrix)': 'CRMT',
  'Handled by': 'UK',
  'Queue Name': 'Retail CCT',
  'Comments': '',
  'Queue Name Display on Genesys': 'X RES Customer CET'},
 {'REASON OF TRANSFER': 'Complaint about the Store or Store Staff',
  'Descriptive Reason of Transfer': 'Complaint regarding store - store staff rude behaviour, stolen, theft,  etc anything happenned on store',
  'DEPARTMENT': 'RCET Retail Complaint Resolution (Warm transfer)',
  'Dept(transfermatrix)': 'CRMT',
  'Handled by': 'UK',
  'Queue Name': 'Retail CCT',
  'Comments': '',
  'Queue Name Display on Genesys': 'X RES Customer CET'},
 {'REASON OF TRANSFER': 'Returns Not Credited',
  'Descriptive Reason of Transfer': 'Returns not credited',
  'DEPARTMENT': 'Returns Not Credited',
  'Dept(transfermatrix)': '',
  'Handled by': 'Pune',
  'Queue Name': 'Pune Team',
  'Comments': 'If nt trained then RNC',
  'Queue Name Display on Genesys': 'X RNC'},
 {'REASON OF TRANSFER': 'Store calling - Wanted to check the customer notes, as returns were done incorrectly',
  'Descriptive Reason of Transfer': 'Store calling - Wanted to check the customer notes, as returns were done incorrectly',
  'DEPARTMENT': 'Returns Not Credited',
  'Dept(transfermatrix)': '',
  'Handled by': 'Pune',
  'Queue Name': 'Pune Team',
  'Comments': 'If nt trained then RNC',
  'Queue Name Display on Genesys': 'X RNC'},
 {'REASON OF TRANSFER': 'Returns Credited to Wrong Account at Store',
  'Descriptive Reason of Transfer': 'Returns Credited to Wrong Account at Store',
  'DEPARTMENT': 'Returns Not Credited',
  'Dept(transfermatrix)': '',
  'Handled by': 'Pune',
  'Queue Name': 'Pune Team',
  'Comments': 'If nt trained then RNC',
  'Queue Name Display on Genesys': 'X RNC'},
 {'REASON OF TRANSFER': 'Store Refunds',
  'Descriptive Reason of Transfer': 'Store Refunds',
  'DEPARTMENT': 'RNC',
  'Dept(transfermatrix)': '',
  'Handled by': 'Pune',
  'Queue Name': 'Pune Team',
  'Comments': 'If nt trained then RNC',
  'Queue Name Display on Genesys': 'X RNC'},
 {'REASON OF TRANSFER': 'Statement Copy Not received',
  'Descriptive Reason of Transfer': 'Customer will say that he has not received the statement copy - advisor can pseudo login or it can be downloaded and sent via post',
  'DEPARTMENT': 'Statements',
  'Dept(transfermatrix)': '',
  'Handled by': 'Pune',
  'Queue Name': 'UK Enquiries',
  'Comments': '',
  'Queue Name Display on Genesys': 'X Enquiries'},
 {'REASON OF TRANSFER': 'Store calling to get transaction details for retail purchased (faulty) item',
  'Descriptive Reason of Transfer': 'Store calling to get transaction details for retail purchased (faulty) item',
  'DEPARTMENT': 'Store UID',
  'Dept(transfermatrix)': 'Enquiries',
  'Handled by': 'Pune',
  'Queue Name': 'RES ',
  'Comments': '',
  'Queue Name Display on Genesys': ''},
 {'REASON OF TRANSFER': 'Customer wants to Change the Delivery Slot ( Furniture )',
  'Descriptive Reason of Transfer': 'Customer wants to Change the Delivery Slot ( Furniture )',
  'DEPARTMENT': 'Telebooking',
  'Dept(transfermatrix)': 'Home',
  'Handled by': 'Pune',
  'Queue Name': 'UK telebooking',
  'Comments': '',
  'Queue Name Display on Genesys': 'X UK Telebooking'},
 {'REASON OF TRANSFER': 'Customer wants to Book a Furniture Delivery',
  'Descriptive Reason of Transfer': 'Customer wants to Book a Furniture Delivery',
  'DEPARTMENT': 'Telebooking',
  'Dept(transfermatrix)': 'Home',
  'Handled by': 'Pune',
  'Queue Name': 'UK telebooking',
  'Comments': '',
  'Queue Name Display on Genesys': 'X UK Telebooking'},
 {'REASON OF TRANSFER': 'Large Furniture Item Query',
  'Descriptive Reason of Transfer': 'Large Furniture Item Query',
  'DEPARTMENT': 'Telebooking',
  'Dept(transfermatrix)': 'Home',
  'Handled by': 'Pune',
  'Queue Name': 'UK telebooking',
  'Comments': '',
  'Queue Name Display on Genesys': 'X UK Telebooking'},
 {'REASON OF TRANSFER': 'DHL Delivery for an Item purchased at a Store',
  'Descriptive Reason of Transfer': 'Customer will say it is a furniture item purchases at a store',
  'DEPARTMENT': 'Telebooking',
  'Dept(transfermatrix)': 'Home',
  'Handled by': 'Pune',
  'Queue Name': 'UK telebooking',
  'Comments': '',
  'Queue Name Display on Genesys': 'X UK Telebooking'},
 {'REASON OF TRANSFER': 'Faulty Item purchased from the Store (N ACCOUNT)',
  'Descriptive Reason of Transfer': 'Faulty Item purchased from the Store (N ACCOUNT) - Account starting from N',
  'DEPARTMENT': 'Warm transfer to store manager',
  'Dept(transfermatrix)': '',
  'Handled by': 'UK',
  'Queue Name': 'Pune Team',
  'Comments': 'We will ask cx to vist store. If nt trained then transfer to Store Service Team',
  'Queue Name Display on Genesys': 'X Store customer calls'},
 {'REASON OF TRANSFER': 'Wrong Goods Sent',
  'Descriptive Reason of Transfer': 'Wrong Goods Sent',
  'DEPARTMENT': 'WGS',
  'Dept(transfermatrix)': '',
  'Handled by': 'Pune',
  'Queue Name': 'Pune Team',
  'Comments': '',
  'Queue Name Display on Genesys': ''},
 {'REASON OF TRANSFER': 'High Claims',
  'Descriptive Reason of Transfer': 'Iguide - claim stage - Investigate and then transfer',
  'DEPARTMENT': 'Claims',
  'Dept(transfermatrix)': 'Enquiries',
  'Handled by': 'UK',
  'Queue Name': 'High Claims',
  'Comments': '',
  'Queue Name Display on Genesys': 'X high claims'},
 {'REASON OF TRANSFER': 'Pay in 3 (N3S) account query',
  'Descriptive Reason of Transfer': 'All N3S accounts to be transferred',
  'DEPARTMENT': ' Pay in 3 Enquiries',
  'Dept(transfermatrix)': 'Enquiries',
  'Handled by': 'UK',
  'Queue Name': 'Pay in 3 Enquiries',
  'Comments': '',
  'Queue Name Display on Genesys': 'X Pay in 3 enquiries'}]






# reason_matrix_dict =[{'REASON OF TRANSFER': 'DD Delivery',
#   'DEPARTMENT': ' UK Telebooking',
#   'Dept(transfermatrix)': 'TP',
#   'Handled by': 'UK',
#   'Queue Name': 'Branded',
#   'Comments': '',
#   'Queue Name Display on Genesys': 'X Branded'},
#  {'REASON OF TRANSFER': 'Account Closure',
#   'DEPARTMENT': 'Account Closure',
#   'Dept(transfermatrix)': '',
#   'Handled by': 'UK & Pune',
#   'Queue Name': 'UK Enquiries',
#   'Comments': 'If not trained',
#   'Queue Name Display on Genesys': 'X  Enquiries'},
#  {'REASON OF TRANSFER': 'N-Orders (Store Calling - Parcel anything apart from At Shop )',
#   'DEPARTMENT': 'Advise the Store to speak with the store manager. Offer a refund/ reorder at the store',
#   'Dept(transfermatrix)': '',
#   'Handled by': 'UK',
#   'Queue Name': 'N - Orders we only track the order and any refund/ Replacement need to dela by store',
#   'Comments': 'If not trained can be transfer to Enq',
#   'Queue Name Display on Genesys': 'X  Enquiries'},
#  {'REASON OF TRANSFER': 'Accounts blocked with AIT investigation',
#   'DEPARTMENT': 'AIT TEAM (Fraud) (Warm transfer)',
#   'Dept(transfermatrix)': 'CCAIT',
#   'Handled by': 'UK',
#   'Queue Name': 'AIT',
#   'Comments': 'Warm transfer',
#   'Queue Name Display on Genesys': 'X AIT'},
#  {'REASON OF TRANSFER': 'Accounts opened without consent',
#   'DEPARTMENT': 'AIT TEAM (Fraud) (Warm transfer)',
#   'Dept(transfermatrix)': 'CCAIT',
#   'Handled by': 'UK',
#   'Queue Name': 'AIT',
#   'Comments': 'Warm transfer',
#   'Queue Name Display on Genesys': 'X AIT'},
#  {'REASON OF TRANSFER': "Orders placed on the account without customer's consent",
#   'DEPARTMENT': 'AIT TEAM (Fraud) (Warm transfer)',
#   'Dept(transfermatrix)': 'CCAIT',
#   'Handled by': 'UK',
#   'Queue Name': 'AIT',
#   'Comments': 'Warm transfer',
#   'Queue Name Display on Genesys': 'X AIT'},
#  {'REASON OF TRANSFER': 'Bank/Directory card used without consent',
#   'DEPARTMENT': 'AIT TEAM (Fraud) (Warm transfer)',
#   'Dept(transfermatrix)': 'CCAIT',
#   'Handled by': 'UK',
#   'Queue Name': 'AIT',
#   'Comments': 'Warm transfer',
#   'Queue Name Display on Genesys': 'X AIT'},
#  {'REASON OF TRANSFER': "Details changed on account without customer's consent",
#   'DEPARTMENT': 'AIT TEAM (Fraud) (Warm transfer)',
#   'Dept(transfermatrix)': 'CCAIT',
#   'Handled by': 'UK',
#   'Queue Name': 'AIT',
#   'Comments': 'Warm transfer',
#   'Queue Name Display on Genesys': 'X AIT'},
#  {'REASON OF TRANSFER': 'Long term occupier calling for customer not known at address, based on an application letter being received',
#   'DEPARTMENT': 'AIT TEAM (Fraud) (Warm transfer)',
#   'Dept(transfermatrix)': 'CCAIT',
#   'Handled by': 'UK',
#   'Queue Name': 'UK Enquiries',
#   'Comments': 'Will set up Gone away on the acocunt. If nt trained can be transfer to Enq',
#   'Queue Name Display on Genesys': 'X  Enquiries'},
#  {'REASON OF TRANSFER': 'Giftcard placed on hold for investigation',
#   'DEPARTMENT': 'AIT TEAM (Fraud) (Warm transfer)',
#   'Dept(transfermatrix)': 'CCAIT',
#   'Handled by': 'UK',
#   'Queue Name': 'Gift card team',
#   'Comments': '',
#   'Queue Name Display on Genesys': 'X gift card'},
#  {'REASON OF TRANSFER': 'N3step AIT Calls',
#   'DEPARTMENT': 'AIT TEAM (Fraud) (Warm transfer)',
#   'Dept(transfermatrix)': 'CCAIT',
#   'Handled by': 'UK',
#   'Queue Name': 'Pay in 3 AIT',
#   'Comments': '',
#   'Queue Name Display on Genesys': 'X Pay in 3 AIT'},
#  {'REASON OF TRANSFER': 'Increasing / Decreasing Credit Limits',
#   'DEPARTMENT': 'C/L Query',
#   'Dept(transfermatrix)': 'Enquiries',
#   'Handled by': 'UK & Pune',
#   'Queue Name': 'UK Enquiries',
#   'Comments': 'If not trained',
#   'Queue Name Display on Genesys': 'X  Enquiries'},
#  {'REASON OF TRANSFER': 'DRL Orders( only when orders are not going through on their account)',
#   'DEPARTMENT': 'CC Payment Queries',
#   'Dept(transfermatrix)': 'Enquiries',
#   'Handled by': 'UK & Pune',
#   'Queue Name': '',
#   'Comments': '',
#   'Queue Name Display on Genesys': ''},
#  {'REASON OF TRANSFER': 'Customer calls to speak to the store',
#   'DEPARTMENT': 'Check if query can be resolved If still required a transfer- Dial 35(Store number)',
#   'Dept(transfermatrix)': '',
#   'Handled by': 'UK & Pune',
#   'Queue Name': 'Specific Store',
#   'Comments': 'First need to check the reason for transferring to the store. If still required then dial Store number and transfer',
#   'Queue Name Display on Genesys': 'Dial Store number on Genesys'},
#  {'REASON OF TRANSFER': 'Collection Not Actioned (  2 or more failed collections )',
#   'DEPARTMENT': 'Transfer to SET ( Senior Enquiries Tam)',
#   'Dept(transfermatrix)': 'Enquiries',
#   'Handled by': 'UK',
#   'Queue Name': 'Escalated Enquiries',
#   'Comments': 'Warm transfer',
#   'Queue Name Display on Genesys': 'X Escalated Enquiries'},
#  {'REASON OF TRANSFER': 'Pending Order',
#   'DEPARTMENT': 'Credit',
#   'Dept(transfermatrix)': 'CCAIT',
#   'Handled by': 'UK & Pune',
#   'Queue Name': 'Credit',
#   'Comments': 'Warm transfer',
#   'Queue Name Display on Genesys': 'X Credit'},
#  {'REASON OF TRANSFER': 'Credit Suspension Query',
#   'DEPARTMENT': 'Credit',
#   'Dept(transfermatrix)': 'CCAIT',
#   'Handled by': 'UK',
#   'Queue Name': 'Credit',
#   'Comments': 'Warm transfer',
#   'Queue Name Display on Genesys': 'X Credit'},
#  {'REASON OF TRANSFER': 'Account Match',
#   'DEPARTMENT': 'Credit',
#   'Dept(transfermatrix)': 'CCAIT',
#   'Handled by': 'UK & Pune',
#   'Queue Name': '',
#   'Comments': '',
#   'Queue Name Display on Genesys': ''},
#  {'REASON OF TRANSFER': 'Store calling for Authorisation code',
#   'DEPARTMENT': 'Credit - Account Queries - Store Cards',
#   'Dept(transfermatrix)': 'CCAIT',
#   'Handled by': 'Pune',
#   'Queue Name': 'Credit',
#   'Comments': 'Store attendant call for the Authorisation code',
#   'Queue Name Display on Genesys': 'X Credit'},
#  {'REASON OF TRANSFER': 'Blocked Account by the Credit Department- Credit Hold',
#   'DEPARTMENT': 'Credit/ Blocked Account by Credit Team',
#   'Dept(transfermatrix)': 'CCAIT',
#   'Handled by': 'UK & Pune',
#   'Queue Name': 'Credit',
#   'Comments': 'Warm transfer',
#   'Queue Name Display on Genesys': 'X Credit'},
#  {'REASON OF TRANSFER': 'Account Opened by customer under 18 yrs of age Accounts Matched',
#   'DEPARTMENT': 'Credit/ Bureau Check Query',
#   'Dept(transfermatrix)': 'CCAIT',
#   'Handled by': 'UK',
#   'Queue Name': 'Credit',
#   'Comments': 'Warm transfer',
#   'Queue Name Display on Genesys': 'X Credit'},
#  {'REASON OF TRANSFER': 'Pended/Scheduled Orders',
#   'DEPARTMENT': 'Credit/ Pended Orders',
#   'Dept(transfermatrix)': 'CCAIT',
#   'Handled by': 'UK & Pune',
#   'Queue Name': 'Credit',
#   'Comments': 'Warm transfer',
#   'Queue Name Display on Genesys': 'X Credit'},
#  {'REASON OF TRANSFER': 'Declined Credit Accounts',
#   'DEPARTMENT': 'Credit/ Withdrawn Support',
#   'Dept(transfermatrix)': 'CCAIT',
#   'Handled by': 'UK',
#   'Queue Name': 'Credit',
#   'Comments': 'Warm transfer',
#   'Queue Name Display on Genesys': 'X Credit'},
#  {'REASON OF TRANSFER': 'Queries regarding cancelled orders',
#   'DEPARTMENT': 'Credit/Cancelled Orders',
#   'Dept(transfermatrix)': 'CCAIT',
#   'Handled by': 'UK',
#   'Queue Name': 'Credit',
#   'Comments': 'Warm transfer',
#   'Queue Name Display on Genesys': 'X Credit'},
#  {'REASON OF TRANSFER': 'Orders Over Credit Limit',
#   'DEPARTMENT': 'Credit/Over C/L Pop up',
#   'Dept(transfermatrix)': 'CCAIT',
#   'Handled by': 'UK & Pune',
#   'Queue Name': 'Credit',
#   'Comments': 'Warm transfer',
#   'Queue Name Display on Genesys': 'X Credit'},
#  {'REASON OF TRANSFER': 'Injury due to a product',
#   'DEPARTMENT': 'CET',
#   'Dept(transfermatrix)': 'CRMT',
#   'Handled by': 'UK',
#   'Queue Name': 'CET',
#   'Comments': 'Warm transfer',
#   'Queue Name Display on Genesys': 'X Online CET'},
#  {'REASON OF TRANSFER': 'Customer has a Reference Number for the Complaint',
#   'DEPARTMENT': 'CET',
#   'Dept(transfermatrix)': 'CRMT',
#   'Handled by': 'UK',
#   'Queue Name': 'CET',
#   'Comments': 'Warm transfer',
#   'Queue Name Display on Genesys': 'X Online CET'},
#  {'REASON OF TRANSFER': 'Direct Debit',
#   'DEPARTMENT': 'Direct Debit',
#   'Dept(transfermatrix)': 'Enquiries',
#   'Handled by': 'Pune',
#   'Queue Name': 'Direct debit',
#   'Comments': 'If nt trained',
#   'Queue Name Display on Genesys': 'X Direct Debit'},
#  {'REASON OF TRANSFER': 'White Goods',
#   'DEPARTMENT': 'DRL',
#   'Dept(transfermatrix)': '',
#   'Handled by': 'UK',
#   'Queue Name': 'DRL ',
#   'Comments': '',
#   'Queue Name Display on Genesys': ''},
#  {'REASON OF TRANSFER': 'Faulty Electrical Items',
#   'DEPARTMENT': 'DRL',
#   'Dept(transfermatrix)': '',
#   'Handled by': 'UK',
#   'Queue Name': 'Pune Home faulty',
#   'Comments': 'If small eclectrical item and delivered by Evri we deal as normal by Pune faulty team and if large Electrical item then Home Pune faulty',
#   'Queue Name Display on Genesys': 'X Pune Faulty Home'},
#  {'REASON OF TRANSFER': 'Expired Directory Card',
#   'DEPARTMENT': 'Enquiries',
#   'Dept(transfermatrix)': 'Enquiries',
#   'Handled by': 'UK & Pune',
#   'Queue Name': 'Enquires',
#   'Comments': 'If not trained',
#   'Queue Name Display on Genesys': 'X  Enquiries'},
#  {'REASON OF TRANSFER': 'Closing an Account',
#   'DEPARTMENT': 'Enquiries',
#   'Dept(transfermatrix)': 'Enquiries',
#   'Handled by': 'UK & Pune',
#   'Queue Name': 'Enquires',
#   'Comments': 'If not trained',
#   'Queue Name Display on Genesys': 'X  Enquiries'},
#  {'REASON OF TRANSFER': 'VIP Sales ( If customer not happy with slots or have not received VIP Invite )',
#   'DEPARTMENT': 'Enquiries',
#   'Dept(transfermatrix)': 'Enquiries',
#   'Handled by': 'UK & Pune',
#   'Queue Name': 'Pune Team',
#   'Comments': 'Not to Transfer',
#   'Queue Name Display on Genesys': ''},
#  {'REASON OF TRANSFER': 'Convertion to a Flexible Account',
#   'DEPARTMENT': 'Enquiries',
#   'Dept(transfermatrix)': 'Enquiries',
#   'Handled by': 'UK',
#   'Queue Name': '',
#   'Comments': '',
#   'Queue Name Display on Genesys': ''},
#  {'REASON OF TRANSFER': 'NEXT Branded Small Electrical Items, delivered by Hermes or Purchased at a Store',
#   'DEPARTMENT': 'Enquiries',
#   'Dept(transfermatrix)': 'Enquiries',
#   'Handled by': 'UK',
#   'Queue Name': 'Branded Team',
#   'Comments': '',
#   'Queue Name Display on Genesys': 'X Branded'},
#  {'REASON OF TRANSFER': 'NEXT watch battery replacement / repair',
#   'DEPARTMENT': 'Enquiries',
#   'Dept(transfermatrix)': 'Enquiries',
#   'Handled by': 'UK',
#   'Queue Name': 'Pune Team',
#   'Comments': 'Not to transfer',
#   'Queue Name Display on Genesys': ''},
#  {'REASON OF TRANSFER': 'Query regarding PPI on the Directory Card',
#   'DEPARTMENT': 'Enquiries',
#   'Dept(transfermatrix)': 'Enquiries',
#   'Handled by': 'UK',
#   'Queue Name': '',
#   'Comments': '',
#   'Queue Name Display on Genesys': ''},
#  {'REASON OF TRANSFER': 'DPD Queries',
#   'DEPARTMENT': 'Enquiries',
#   'Dept(transfermatrix)': 'Enquiries',
#   'Handled by': 'UK & Pune',
#   'Queue Name': 'Pune Team',
#   'Comments': 'Not to transfer',
#   'Queue Name Display on Genesys': ''},
#  {'REASON OF TRANSFER': 'ParcelShop Queries',
#   'DEPARTMENT': 'Enquiries',
#   'Dept(transfermatrix)': 'Enquiries',
#   'Handled by': 'UK & Pune',
#   'Queue Name': 'Pune Team',
#   'Comments': 'Not to transfer',
#   'Queue Name Display on Genesys': ''},
#  {'REASON OF TRANSFER': 'Query on International Retail order',
#   'DEPARTMENT': 'Enquiries',
#   'Dept(transfermatrix)': 'Enquiries',
#   'Handled by': 'ROW',
#   'Queue Name': 'International ',
#   'Comments': '',
#   'Queue Name Display on Genesys': 'X International'},
#  {'REASON OF TRANSFER': 'If the customer is not willing to visit the store',
#   'DEPARTMENT': 'Enquiries',
#   'Dept(transfermatrix)': 'Enquiries',
#   'Handled by': 'UK/Pune',
#   'Queue Name': 'Pune Team',
#   'Comments': 'Not to transfer',
#   'Queue Name Display on Genesys': ''},
#  {'REASON OF TRANSFER': 'Faulty Item',
#   'DEPARTMENT': 'Faulty Items',
#   'Dept(transfermatrix)': 'Enquiries',
#   'Handled by': 'Pune',
#   'Queue Name': 'Pune Team',
#   'Comments': 'Not to transfer',
#   'Queue Name Display on Genesys': ''},
#  {'REASON OF TRANSFER': 'Flower Query',
#   'DEPARTMENT': 'Flower Enquiries',
#   'Dept(transfermatrix)': 'Enquiries',
#   'Handled by': 'Pune',
#   'Queue Name': 'Flower Enquiries',
#   'Comments': 'If nt trained',
#   'Queue Name Display on Genesys': 'X flower Enquiries'},
#  {'REASON OF TRANSFER': 'Gift Card Query',
#   'DEPARTMENT': 'Gift Card Enquiries',
#   'Dept(transfermatrix)': 'Enquiries',
#   'Handled by': 'UK',
#   'Queue Name': 'Gift Card Team',
#   'Comments': 'X gift Card',
#   'Queue Name Display on Genesys': ''},
#  {'REASON OF TRANSFER': 'Request to speak to the HR Department',
#   'DEPARTMENT': 'Give email address- RetailHR_Admin@next.co.uk',
#   'Dept(transfermatrix)': '',
#   'Handled by': 'UK',
#   'Queue Name': 'Next headoffice',
#   'Comments': '',
#   'Queue Name Display on Genesys': 'Next headoffice Reception'},
#  {'REASON OF TRANSFER': 'Goods Not Received',
#   'DEPARTMENT': 'GNR',
#   'Dept(transfermatrix)': 'Enquiries',
#   'Handled by': 'Pune',
#   'Queue Name': 'Pune Team',
#   'Comments': 'If nt trained GNR',
#   'Queue Name Display on Genesys': ''},
#  {'REASON OF TRANSFER': 'Tracking an Order / Parcel',
#   'DEPARTMENT': 'GNR',
#   'Dept(transfermatrix)': 'Enquiries',
#   'Handled by': 'Pune',
#   'Queue Name': 'Pune Team',
#   'Comments': 'If nt trained GNR',
#   'Queue Name Display on Genesys': ''},
#  {'REASON OF TRANSFER': 'Home item regarding complaints',
#   'DEPARTMENT': 'HCRMT (Warm transfer) ',
#   'Dept(transfermatrix)': 'CRMT',
#   'Handled by': 'UK',
#   'Queue Name': 'Home CET',
#   'Comments': '',
#   'Queue Name Display on Genesys': 'X home CET'},
#  {'REASON OF TRANSFER': 'Faulty Home Items',
#   'DEPARTMENT': 'Home',
#   'Dept(transfermatrix)': 'Home',
#   'Handled by': 'UK',
#   'Queue Name': 'Home Pune Faulty',
#   'Comments': '',
#   'Queue Name Display on Genesys': 'X Pune Faulty Home'},
#  {'REASON OF TRANSFER': 'Home Item Query',
#   'DEPARTMENT': 'Home',
#   'Dept(transfermatrix)': 'Home',
#   'Handled by': 'UK',
#   'Queue Name': 'UK telebooking',
#   'Comments': '',
#   'Queue Name Display on Genesys': 'X UK Telebooking'},
#  {'REASON OF TRANSFER': 'Delivery Query of Light and Large items, delivered by next day to Store Vans',
#   'DEPARTMENT': 'Home',
#   'Dept(transfermatrix)': 'Home',
#   'Handled by': 'UK',
#   'Queue Name': '',
#   'Comments': '',
#   'Queue Name Display on Genesys': ''},
#  {'REASON OF TRANSFER': 'Home Item Query not available on the Website',
#   'DEPARTMENT': 'Home',
#   'Dept(transfermatrix)': 'Home',
#   'Handled by': 'UK',
#   'Queue Name': 'Home Team',
#   'Comments': '',
#   'Queue Name Display on Genesys': 'X Home'},
#  {'REASON OF TRANSFER': 'Personalised gift',
#   'DEPARTMENT': 'Home Personalized Gift/Team',
#   'Dept(transfermatrix)': 'Home',
#   'Handled by': 'UK',
#   'Queue Name': 'Personalised Team',
#   'Comments': '',
#   'Queue Name Display on Genesys': 'X Personalised'},
#  {'REASON OF TRANSFER': 'DD Delivery But Personalised',
#   'DEPARTMENT': 'Home Personalized Gift/Team',
#   'Dept(transfermatrix)': 'Home',
#   'Handled by': 'UK',
#   'Queue Name': 'Personalised Team',
#   'Comments': '',
#   'Queue Name Display on Genesys': 'X Personalised'},
#  {'REASON OF TRANSFER': 'Made to Measure Curtains/ Blinds',
#   'DEPARTMENT': 'Home product Management',
#   'Dept(transfermatrix)': 'Home',
#   'Handled by': 'UK',
#   'Queue Name': 'Branded',
#   'Comments': '',
#   'Queue Name Display on Genesys': 'X Branded (IVR - Press 1)'},
#  {'REASON OF TRANSFER': 'Store calling to track order Home or Store Delivery (POS Rollout worktype)',
#   'DEPARTMENT': 'If not trained on worktype please transfer to relevant Dept i.e Store services for Store delivery, GNR for Home Delivery',
#   'Dept(transfermatrix)': '',
#   'Handled by': 'Pune',
#   'Queue Name': 'Pune Team',
#   'Comments': 'If nt trained then Store Service for store order and GNR for online order',
#   'Queue Name Display on Genesys': 'X Store Customer calls'},
#  {'REASON OF TRANSFER': 'Store calling - Customer want to cancel the Order',
#   'DEPARTMENT': 'If retail order- Advise them to cancel in Store/ Online orders deal as normal',
#   'Dept(transfermatrix)': '',
#   'Handled by': 'UK/Pune',
#   'Queue Name': 'Pune Team',
#   'Comments': 'Not to Transfer. If retail order- Advise them to cancel in Store/ Online orders deal as normal',
#   'Queue Name Display on Genesys': '-'},
#  {'REASON OF TRANSFER': 'Refund Not Received on the International Account',
#   'DEPARTMENT': 'International',
#   'Dept(transfermatrix)': 'International',
#   'Handled by': 'ROW',
#   'Queue Name': 'International ',
#   'Comments': '',
#   'Queue Name Display on Genesys': 'X International'},
#  {'REASON OF TRANSFER': 'Techincal Issue with the Next Website',
#   'DEPARTMENT': 'Internet Helpline',
#   'Dept(transfermatrix)': 'Enquiries',
#   'Handled by': 'Pune',
#   'Queue Name': 'Internet helpline',
#   'Comments': 'If nt trained',
#   'Queue Name Display on Genesys': 'X Internet Helpline'},
#  {'REASON OF TRANSFER': 'Light and Large Delivery',
#   'DEPARTMENT': 'Light & Large',
#   'Dept(transfermatrix)': '',
#   'Handled by': 'UK',
#   'Queue Name': 'Pune Team',
#   'Comments': 'Not to Transfer',
#   'Queue Name Display on Genesys': ''},
#  {'REASON OF TRANSFER': 'Store calling for POS number',
#   'DEPARTMENT': "Locate the POS No on website with the help of item description, if not able to locate, ask the S/A to speak with Store Manager as it would be the manager's descretion",
#   'Dept(transfermatrix)': '',
#   'Handled by': 'UK/Pune',
#   'Queue Name': 'Pune Team',
#   'Comments': "Locate the POS No on website with the help of item description, if not able to locate, ask the S/A to speak with Store Manager as it would be the manager's descretion",
#   'Queue Name Display on Genesys': ''},
#  {'REASON OF TRANSFER': 'Vulnerable Customer who are not claiming financial difficulties',
#   'DEPARTMENT': 'Customer Care Team (Warm transfer)',
#   'Dept(transfermatrix)': '',
#   'Handled by': 'UK',
#   'Queue Name': 'Collection Team',
#   'Comments': '',
#   'Queue Name Display on Genesys': 'X collections'},
#  {'REASON OF TRANSFER': 'Account charges',
#   'DEPARTMENT': 'Payment / Account Queries',
#   'Dept(transfermatrix)': 'Enquiries',
#   'Handled by': 'UK/Pune',
#   'Queue Name': 'UK Enquiries',
#   'Comments': 'If query on Interest charges then UK enq/ Refin query then deal as normal',
#   'Queue Name Display on Genesys': 'X Enquiries'},
#  {'REASON OF TRANSFER': 'Payment / Account Query',
#   'DEPARTMENT': 'Payment / Account Queries',
#   'Dept(transfermatrix)': 'Enquiries',
#   'Handled by': 'UK/Pune',
#   'Queue Name': 'UK Enquiries',
#   'Comments': '',
#   'Queue Name Display on Genesys': 'X Enquiries'},
#  {'REASON OF TRANSFER': 'Store Calling for TILL Issue',
#   'DEPARTMENT': 'POS Control',
#   'Dept(transfermatrix)': 'Non-Operation',
#   'Handled by': 'UK',
#   'Queue Name': '',
#   'Comments': '',
#   'Queue Name Display on Genesys': ''},
#  {'REASON OF TRANSFER': 'Customer wants to Cancel the Delivery ( Furniture )',
#   'DEPARTMENT': 'Pune telbooking',
#   'Dept(transfermatrix)': 'Home',
#   'Handled by': 'Pune',
#   'Queue Name': 'Pune Team',
#   'Comments': 'Apply Macro',
#   'Queue Name Display on Genesys': ''},
#  {'REASON OF TRANSFER': 'Complaint regarding store',
#   'DEPARTMENT': 'RCET Retail Complaint Resolution (Warm transfer)',
#   'Dept(transfermatrix)': 'CRMT',
#   'Handled by': 'UK',
#   'Queue Name': 'Retail CCT',
#   'Comments': '',
#   'Queue Name Display on Genesys': 'X RES Customer CET'},
#  {'REASON OF TRANSFER': 'Customer has a Reference Number for the retail Complaint',
#   'DEPARTMENT': 'RCET Retail Complaint Resolution (Warm transfer)',
#   'Dept(transfermatrix)': 'CRMT',
#   'Handled by': 'UK',
#   'Queue Name': 'Retail CCT',
#   'Comments': '',
#   'Queue Name Display on Genesys': 'X RES Customer CET'},
#  {'REASON OF TRANSFER': 'Complaint about the Store or Store Staff',
#   'DEPARTMENT': 'RCET Retail Complaint Resolution (Warm transfer)',
#   'Dept(transfermatrix)': 'CRMT',
#   'Handled by': 'UK',
#   'Queue Name': 'Retail CCT',
#   'Comments': '',
#   'Queue Name Display on Genesys': 'X RES Customer CET'},
#  {'REASON OF TRANSFER': 'Returns Not Credited',
#   'DEPARTMENT': 'Returns Not Credited',
#   'Dept(transfermatrix)': '',
#   'Handled by': 'Pune',
#   'Queue Name': 'Pune Team',
#   'Comments': 'If nt trained then RNC',
#   'Queue Name Display on Genesys': 'X RNC'},
#  {'REASON OF TRANSFER': 'Store calling - Wanted to check the customer notes, as returns were done incorrectly',
#   'DEPARTMENT': 'Returns Not Credited',
#   'Dept(transfermatrix)': '',
#   'Handled by': 'Pune',
#   'Queue Name': 'Pune Team',
#   'Comments': 'If nt trained then RNC',
#   'Queue Name Display on Genesys': 'X RNC'},
#  {'REASON OF TRANSFER': 'Returns Credited to Wrong Account at Store',
#   'DEPARTMENT': 'Returns Not Credited',
#   'Dept(transfermatrix)': '',
#   'Handled by': 'Pune',
#   'Queue Name': 'Pune Team',
#   'Comments': 'If nt trained then RNC',
#   'Queue Name Display on Genesys': 'X RNC'},
#  {'REASON OF TRANSFER': 'Store Refunds',
#   'DEPARTMENT': 'RNC',
#   'Dept(transfermatrix)': '',
#   'Handled by': 'Pune',
#   'Queue Name': 'Pune Team',
#   'Comments': 'If nt trained then RNC',
#   'Queue Name Display on Genesys': 'X RNC'},
#  {'REASON OF TRANSFER': 'Statement Copy Not received',
#   'DEPARTMENT': 'Statements',
#   'Dept(transfermatrix)': '',
#   'Handled by': 'Pune',
#   'Queue Name': 'UK Enquiries',
#   'Comments': '',
#   'Queue Name Display on Genesys': 'X Enquiries'},
#  {'REASON OF TRANSFER': 'Store calling to get transaction details for retail purchased (faulty) item',
#   'DEPARTMENT': 'Store UID',
#   'Dept(transfermatrix)': 'Enquiries',
#   'Handled by': 'Pune',
#   'Queue Name': 'RES ',
#   'Comments': '',
#   'Queue Name Display on Genesys': ''},
#  {'REASON OF TRANSFER': 'Customer wants to Change the Delivery Slot ( Furniture )',
#   'DEPARTMENT': 'Telebooking',
#   'Dept(transfermatrix)': 'Home',
#   'Handled by': 'Pune',
#   'Queue Name': 'UK telebooking',
#   'Comments': '',
#   'Queue Name Display on Genesys': 'X UK Telebooking'},
#  {'REASON OF TRANSFER': 'Customer wants to Book a Furniture Delivery',
#   'DEPARTMENT': 'Telebooking',
#   'Dept(transfermatrix)': 'Home',
#   'Handled by': 'Pune',
#   'Queue Name': 'UK telebooking',
#   'Comments': '',
#   'Queue Name Display on Genesys': 'X UK Telebooking'},
#  {'REASON OF TRANSFER': 'Large Furniture Item Query',
#   'DEPARTMENT': 'Telebooking',
#   'Dept(transfermatrix)': 'Home',
#   'Handled by': 'Pune',
#   'Queue Name': 'UK telebooking',
#   'Comments': '',
#   'Queue Name Display on Genesys': 'X UK Telebooking'},
#  {'REASON OF TRANSFER': 'DHL Delivery for an Item purchased at a Store',
#   'DEPARTMENT': 'Telebooking',
#   'Dept(transfermatrix)': 'Home',
#   'Handled by': 'Pune',
#   'Queue Name': 'UK telebooking',
#   'Comments': '',
#   'Queue Name Display on Genesys': 'X UK Telebooking'},
#  {'REASON OF TRANSFER': 'Faulty Item purchased from the Store (N ACCOUNT)',
#   'DEPARTMENT': 'Warm transfer to store manager',
#   'Dept(transfermatrix)': '',
#   'Handled by': 'UK',
#   'Queue Name': 'Pune Team',
#   'Comments': 'We will ask cx to vist store. If nt trained then transfer to Store Service Team',
#   'Queue Name Display on Genesys': 'X Store customer calls'},
#  {'REASON OF TRANSFER': 'Wrong Goods Sent',
#   'DEPARTMENT': 'WGS',
#   'Dept(transfermatrix)': '',
#   'Handled by': 'Pune',
#   'Queue Name': 'Pune Team',
#   'Comments': '',
#   'Queue Name Display on Genesys': ''},
#  {'REASON OF TRANSFER': 'High Claims',
#   'DEPARTMENT': 'Claims',
#   'Dept(transfermatrix)': 'Enquiries',
#   'Handled by': 'UK',
#   'Queue Name': 'High Claims',
#   'Comments': '',
#   'Queue Name Display on Genesys': 'X high claims'},
#  {'REASON OF TRANSFER': 'Pay in 3 (N3S) account query',
#   'DEPARTMENT': ' Pay in 3 Enquiries',
#   'Dept(transfermatrix)': 'Enquiries',
#   'Handled by': 'UK',
#   'Queue Name': 'Pay in 3 Enquiries',
#   'Comments': '',
#   'Queue Name Display on Genesys': 'X Pay in 3 enquiries'}]
